# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x10slack.message.v1\"[\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nchannel_id\x18\x02 \x01(\t\x12\x0e\n\x06sender\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\x03\"F\n\x12SendMessageRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\"A\n\x13SendMessageResponse\x12*\n\x07message\x18\x01 \x01(\x0b\x32\x19.slack.message.v1.Message\"(\n\x12GetMessagesRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\t\"B\n\x13GetMessagesResponse\x12+\n\x08messages\x18\x01 \x03(\x0b\x32\x19.slack.message.v1.Message2\xc8\x01\n\x0eMessageService\x12Z\n\x0bSendMessage\x12$.slack.message.v1.SendMessageRequest\x1a%.slack.message.v1.SendMessageResponse\x12Z\n\x0bGetMessages\x12$.slack.message.v1.GetMessagesRequest\x1a%.slack.message.v1.GetMessagesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=35
  _globals['_MESSAGE']._serialized_end=126
  _globals['_SENDMESSAGEREQUEST']._serialized_start=128
  _globals['_SENDMESSAGEREQUEST']._serialized_end=198
  _globals['_SENDMESSAGERESPONSE']._serialized_start=200
  _globals['_SENDMESSAGERESPONSE']._serialized_end=265
  _globals['_GETMESSAGESREQUEST']._serialized_start=267
  _globals['_GETMESSAGESREQUEST']._serialized_end=307
  _globals['_GETMESSAGESRESPONSE']._serialized_start=309
  _globals['_GETMESSAGESRESPONSE']._serialized_end=375
  _globals['_MESSAGESERVICE']._serialized_start=378
  _globals['_MESSAGESERVICE']._serialized_end=578
# @@protoc_insertion_point(module_scope)
