# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import message_pb2 as message__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in message_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessageServiceStub:
    """---------------------------------------------------------------------------
    The service: a named collection of RPC methods.

    Each "rpc" line is: method name, request type (in parens), returns, response
    type (in parens). Both of ours are UNARY — one request in, one response out
    (the plain request→response shape). The "stream" keyword, which we're
    deferring, would turn either side into a stream.
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/slack.message.v1.MessageService/SendMessage',
                request_serializer=message__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=message__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.GetMessages = channel.unary_unary(
                '/slack.message.v1.MessageService/GetMessages',
                request_serializer=message__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=message__pb2.GetMessagesResponse.FromString,
                _registered_method=True)


class MessageServiceServicer:
    """---------------------------------------------------------------------------
    The service: a named collection of RPC methods.

    Each "rpc" line is: method name, request type (in parens), returns, response
    type (in parens). Both of ours are UNARY — one request in, one response out
    (the plain request→response shape). The "stream" keyword, which we're
    deferring, would turn either side into a stream.
    ---------------------------------------------------------------------------
    """

    def SendMessage(self, request, context):
        """Write one message, get the stored version back.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """Read all messages in a channel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=message__pb2.SendMessageRequest.FromString,
                    response_serializer=message__pb2.SendMessageResponse.SerializeToString,
            ),
            'GetMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=message__pb2.GetMessagesRequest.FromString,
                    response_serializer=message__pb2.GetMessagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'slack.message.v1.MessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('slack.message.v1.MessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageService:
    """---------------------------------------------------------------------------
    The service: a named collection of RPC methods.

    Each "rpc" line is: method name, request type (in parens), returns, response
    type (in parens). Both of ours are UNARY — one request in, one response out
    (the plain request→response shape). The "stream" keyword, which we're
    deferring, would turn either side into a stream.
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slack.message.v1.MessageService/SendMessage',
            message__pb2.SendMessageRequest.SerializeToString,
            message__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slack.message.v1.MessageService/GetMessages',
            message__pb2.GetMessagesRequest.SerializeToString,
            message__pb2.GetMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
